# Generated by Django 4.1.5 on 2023-03-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PETSHOPAPPS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give', models.CharField(max_length=5)),
                ('adopt', models.CharField(max_length=5)),
                ('vetinary', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='loggin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
