# Generated by Django 4.1.5 on 2023-03-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PETSHOPAPPS', '0002_adop_loggin'),
    ]

    operations = [
        migrations.CreateModel(
            name='givee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('breed', models.CharField(max_length=25)),
                ('age', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('phonenumber', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='adop',
        ),
    ]
