# Generated by Django 4.1.5 on 2023-03-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PETSHOPAPPS', '0003_givee_delete_adop'),
    ]

    operations = [
        migrations.CreateModel(
            name='adoptcuss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='givee',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
