# Generated by Django 4.1.5 on 2023-03-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PETSHOPAPPS', '0004_adoptcuss_alter_givee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='givee',
            old_name='color',
            new_name='colour',
        ),
        migrations.RenameField(
            model_name='givee',
            old_name='phonenumber',
            new_name='number',
        ),
    ]
