# Generated by Django 4.1.5 on 2023-03-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PETSHOPAPPS', '0005_rename_color_givee_colour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccinedate', models.DateField(max_length=25)),
            ],
        ),
    ]
