# Generated by Django 4.1.5 on 2023-03-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PETSHOPAPPS', '0006_vacc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacc',
            name='vaccinedate',
            field=models.DateField(),
        ),
    ]
