# Generated by Django 4.1.5 on 2023-04-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PETSHOPAPPS', '0007_alter_vacc_vaccinedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacc',
            name='vaccinedate',
            field=models.DateField(max_length=20),
        ),
    ]
