# Generated by Django 4.1.5 on 2023-04-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PETSHOPAPPS', '0008_alter_vacc_vaccinedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=11)),
                ('message', models.CharField(max_length=11)),
            ],
        ),
    ]
