# Generated by Django 4.1.5 on 2023-04-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PETSHOPAPPS', '0010_contactt_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='adoptt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('breed', models.CharField(max_length=25)),
                ('age', models.CharField(max_length=25)),
                ('colour', models.CharField(max_length=25)),
                ('number', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('file', models.FileField(default=0, upload_to='')),
                ('uid', models.IntegerField(max_length=40)),
            ],
        ),
    ]
