# Generated by Django 4.1.5 on 2023-04-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PETSHOPAPPS', '0011_adoptt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adoptt',
        ),
    ]
