# Generated by Django 4.1.5 on 2023-04-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PETSHOPAPPS', '0012_delete_adoptt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givee',
            name='image',
        ),
        migrations.AddField(
            model_name='givee',
            name='file',
            field=models.FileField(default='0', upload_to=''),
        ),
    ]
