# Generated by Django 4.1.5 on 2023-04-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PETSHOPAPPS', '0013_remove_givee_image_givee_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='dewo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dewormdate', models.DateField(max_length=20)),
            ],
        ),
    ]
