# Generated by Django 4.1.5 on 2023-04-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PETSHOPAPPS', '0014_dewo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givee',
            name='file',
        ),
        migrations.AddField(
            model_name='givee',
            name='image',
            field=models.ImageField(default='0', upload_to=''),
        ),
    ]
