# Generated by Django 4.1.5 on 2023-04-28 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PETSHOPAPPS', '0015_remove_givee_file_givee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='givee',
            old_name='state',
            new_name='price',
        ),
    ]
