# Generated by Django 4.1.5 on 2023-04-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PETSHOPAPPS', '0016_rename_state_givee_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='role',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
